name: Test
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        node-version: [16, 18, 20, 22]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm test
