name: Test
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm test
    - run: npm run coverage
    - run: mv coverage/coverage-final.json coverage/coverage.json
    - name: Update Coverage Badge
      if: (github.ref == format('refs/heads/{0}', github.event.repository.default_branch)) && matrix.node-version == 22
      uses: we-cli/coverage-badge-action@main
